### ISSUE TITLE
Restaurant admin actions set up for milestone

### ISSUE THREAD

**Issue by Simon-157** [Simon-157/fast-foodies#8]
- [x] Register a restaurant controller
 

- [x]  Authenticate A restaurant admin

- [x]  Add menu action by restaurant admin

- [x]  Delete menu action by restaurant admin

- [x] Update menu action by restaurant admin
- [x]  Query published menus on both the restaurant side and the client side for consumers
